# Generated by Django 5.0.3 on 2024-03-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='description',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='stock',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
